
GET http://localhost:8080/api/items/getitems


###
POST http://localhost:8080/api/items/postitems
Content-Type: application/json

{
    "name": "Jalebi",
    "price": 7,
    "category": "dessert",
    "image": "https://www.bitesbee.com/wp-content/uploads/2021/09/Jalebi.jpg"
}

###
PUT http://localhost:8080/api/items/66235c8e507155de889e5b34
Content-Type: application/json

{
    "name": "Jalebi",
    "price": 10,
    "category": "breakfast",
    "image": "https://www.palatesdesire.com/wp-content/uploads/2022/09/Mysore-masala-dosa-recipe@palates-desire.jpg"
}

###
DELETE http://localhost:8080/api/items/66235c8e507155de889e5b34


###
GET http://localhost:8080/api/items/65c90a7a3a38083f90cd04f6


###
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
    "name":"mayuresh",
    "empId":10,
    "password":"mayuresh"
}

###
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
    "empId":1,
    "password":"test"
}


###
GET http://localhost:8080/api/orders/getorders

###
POST http://localhost:8080/api/orders/postorder
Content-Type: application/json

{
    "billNumber": 1234,
    "contactNumber": "9876543210",
    "customerName": "John Doe",
    "hostName": "Cashier1",
    "order": [{"name": "Pizza", "price": 200, "quantity": 2}],
    "orderNumber": 5678,
    "paymentOption": "Cash",
    "subTotal": 400,
    "tax": 20,
    "total": 420
}

###
GET http://localhost:8080/api/reports/get-today-sales